project:
  type: website
  output-dir: _site

website:
  title: "RSECon22"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - jordan.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
